# Generated by Django 4.2.3 on 2023-07-11 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_post_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="postdate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 11, 7, 46, 55, 878799, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
